const SCRAP_DATE = "05/04/2024";
let MAX_VUES = 0;
let MAX_TIME = 0;

const dataDirect = [
    {
        rawTime: "2:36:30  ",
        rawVues: "148k",
        title: "Intelligence artificielle, bullsh*t, pipotron ? Benjamin Bayart [EN DIRECT]",
        time: 9390,
        vues: 148000,
    },
    {
        rawTime: "3:41:22  ",
        rawVues: "463k",
        title: "Comprendre la guerre qui vient ? Henri Guaino [EN DIRECT]",
        time: 13282,
        vues: 463000,
    },
    {
        rawTime: "2:30:34  ",
        rawVues: "247k",
        title: "Les Hackers face aux cyberguerres ? Bluetouff, Fabrice Epelboin et Marc-Antoine Ledieu [EN DIRECT]",
        time: 9034,
        vues: 247000,
    },
    {
        rawTime: "1:18:08  ",
        rawVues: "125k",
        title: "Animateur télé et show-business ? Valérie Damidot [EN DIRECT]",
        time: 4688,
        vues: 125000,
    },
    {
        rawTime: "2:24:17  ",
        rawVues: "247k",
        title: "Rendre compte des catastrophes énergétiques et humanitaires ? Quentin Müller [EN DIRECT]",
        time: 8657,
        vues: 247000,
    },
    {
        rawTime: "2:31:09  ",
        rawVues: "481k",
        title: "Économie : le mensonge face à la réalité ? Marc Touati [EN DIRECT]",
        time: 9069,
        vues: 481000,
    },
    {
        rawTime: "1:47:02  ",
        rawVues: "581k",
        title: "Fichage politique, où va la France ? Marion Maréchal [EN DIRECT]",
        time: 6422,
        vues: 581000,
    },
    {
        rawTime: "2:53:08  ",
        rawVues: "207k",
        title: "La mort de l'agriculture française ? Pierrick Horel et Quentin Le Guillous [EN DIRECT]",
        time: 10388,
        vues: 207000,
    },
    {
        rawTime: "2:08:19  ",
        rawVues: "303k",
        title: "Mon Afrique va mal ? Tiken Jah Fakoly [EN DIRECT]",
        time: 7699,
        vues: 303000,
    },
    {
        rawTime: "2:59:37  ",
        rawVues: "254k",
        title: "La Finance peut-elle arrêter de ruiner la planète ? Bertrand Badré [EN DIRECT]",
        time: 10777,
        vues: 254000,
    },
    {
        rawTime: "1:55:16  ",
        rawVues: "882k",
        title: "Fabrice Éboué, plus rien à perdre ? [EN DIRECT]",
        time: 6916,
        vues: 882000,
    },
    {
        rawTime: "2:24:08  ",
        rawVues: "335k",
        title: "Inflation, bientôt la révolution ? Dominique Schelcher [EN DIRECT]",
        time: 8648,
        vues: 335000,
    },
    {
        rawTime: "2:18:12  ",
        rawVues: "314k",
        title: "Accueillir des migrants avec moins d'énergie ?  O. Delamarche et Charles-Henri Gallois [EN DIRECT]",
        time: 8292,
        vues: 314000,
    },
    {
        rawTime: "2:20:21  ",
        rawVues: "441k",
        title: "Trahison des chefs, où va la France ? Guillaume Bigot [EN DIRECT]",
        time: 8421,
        vues: 441000,
    },
    {
        rawTime: "2:16:16  ",
        rawVues: "385k",
        title: "IA : notre futur assistant ou nouveau maître ? Justine Cassell et Cédric Villani [EN DIRECT]",
        time: 8176,
        vues: 385000,
    },
    {
        rawTime: "2:34:40  ",
        rawVues: "248k",
        title: "Souveraineté alimentaire face au dérèglement climatique ? Serge Zaka [EN DIRECT]",
        time: 9280,
        vues: 248000,
    },
    {
        rawTime: "2:45:46  ",
        rawVues: "304k",
        title: "Deux économistes sous stress-test ? Julia Cagé et Thomas Piketty [EN DIRECT]",
        time: 9946,
        vues: 304000,
    },
    {
        rawTime: "2:09:35  ",
        rawVues: "548k",
        title: "Comment devient-on bourreau ? Pierre Conesa [EN DIRECT]",
        time: 7775,
        vues: 548000,
    },
    {
        rawTime: "1:58:02  ",
        rawVues: "197k",
        title: "Produire en France, au-delà de l'inquiétude ? Loïk Le Floch-Prigent et Nicolas Meilhan [EN DIRECT]",
        time: 7082,
        vues: 197000,
    },
    {
        rawTime: "2:28:06  ",
        rawVues: "624k",
        title: "Dans le mur, quoi qu’il en coûte ? François Lenglet [EN DIRECT]",
        time: 8886,
        vues: 624000,
    },
    {
        rawTime: "2:28:26  ",
        rawVues: "465k",
        title: "IA : le devenir légume de l’humanité ? Éric Sadin [EN DIRECT]",
        time: 8906,
        vues: 465000,
    },
    {
        rawTime: "2:23:42  ",
        rawVues: "456k",
        title: "La faillite du système bancaire ? Jacques de Larosière et Tom Benoit [EN DIRECT]",
        time: 8622,
        vues: 456000,
    },
    {
        rawTime: "1:20:44  ",
        rawVues: "247k",
        title: "Faillite des élites ? Alexandre Moatti [EN DIRECT]",
        time: 4844,
        vues: 247000,
    },
    {
        rawTime: "2:41:07  ",
        rawVues: "677k",
        title: "Bataille de civilisation dans un monde en ruine ? Jean-Luc Mélenchon [EN DIRECT]",
        time: 9667,
        vues: 677000,
    },
    {
        rawTime: "2:18:25  ",
        rawVues: "446k",
        title: "La guerre des intelligences ? Laurent Alexandre [EN DIRECT]",
        time: 8305,
        vues: 446000,
    },
    {
        rawTime: "2:36:22  ",
        rawVues: "1,1Mde",
        title: "Sobriété, déconsommateurs : cache-misère des gouvernements ? Jean-Marc Jancovici [EN DIRECT]",
        time: 9382,
        vues: 1100000,
    },
    {
        rawTime: "1:15:15  ",
        rawVues: "701k",
        title: "Second tour, fable politique ? Albert Dupontel [EN DIRECT]",
        time: 4515,
        vues: 701000,
    },
    {
        rawTime: "2:15:33  ",
        rawVues: "250k",
        title: "Prix Nobel d'économie : face à la pauvreté ? Esther Duflo [EN DIRECT]",
        time: 8133,
        vues: 250000,
    },
    {
        rawTime: "2:44:49  ",
        rawVues: "1Mde",
        title: "Quand est-ce que l'on touche le fond ? Pierre Sabatier et Olivier Delamarche [EN DIRECT]",
        time: 9889,
        vues: 1000000,
    },
    {
        rawTime: "2:43:34  ",
        rawVues: "267k",
        title: "Criminalisation des luttes : écoterrorisme ? M. Dulac, C. Bonneuil, A. Planchard [EN DIRECT]",
        time: 9814,
        vues: 267000,
    },
    {
        rawTime: "1:55:22  ",
        rawVues: "383k",
        title: "Les émeutes de la pauvreté ? Olivier De Schutter [EN DIRECT]",
        time: 6922,
        vues: 383000,
    },
    {
        rawTime: "3:19:15  ",
        rawVues: "815k",
        title: "Stratège de guerre : Sabotages, Cupidité et Agressions ? Jérôme Clech [EN DIRECT]",
        time: 11955,
        vues: 815000,
    },
    {
        rawTime: "2:17:47  ",
        rawVues: "248k",
        title: "Effondrement, pénurie de médicaments ? Clémence Marque [EN DIRECT]",
        time: 8267,
        vues: 248000,
    },
    {
        rawTime: "1:43:28  ",
        rawVues: "361k",
        title: "Immigration, où va la France ? Estelle Youssouffa [EN DIRECT]",
        time: 6208,
        vues: 361000,
    },
    {
        rawTime: "2:19:50  ",
        rawVues: "529k",
        title: "Domination Globale : Taïwan ? Wu Chih-chung [EN DIRECT]",
        time: 8390,
        vues: 529000,
    },
    {
        rawTime: "3:17:20  ",
        rawVues: "1,2Mde",
        title: "Semaine de 4 jours, taxe sur la spéculation ? Pierre Larrouturou [EN DIRECT]",
        time: 11840,
        vues: 1200000,
    },
    {
        rawTime: "2:12:06  ",
        rawVues: "932k",
        title: "France : la stratégie du canard sans tête ? Yves Bréchet [EN DIRECT]",
        time: 7926,
        vues: 932000,
    },
    {
        rawTime: "2:06:25  ",
        rawVues: "320k",
        title: "Analyser un monde anesthésié par l’horreur ? Jean-Jacques Tyszler [EN DIRECT]",
        time: 7585,
        vues: 320000,
    },
    {
        rawTime: "2:00:37  ",
        rawVues: "255k",
        title: "Marchés financiers sans éthique : quels sont les risques ? Eva Sadoun [EN DIRECT]",
        time: 7237,
        vues: 255000,
    },
    {
        rawTime: "2:33:19  ",
        rawVues: "1Mde",
        title: "Où sont les risques, où va la France ? Henri Guaino [EN DIRECT]",
        time: 9199,
        vues: 1000000,
    },
    {
        rawTime: "1:39:24  ",
        rawVues: "356k",
        title: "Qui aurait pu prédire : la guerre économique ? Christian Harbulot [EN DIRECT]",
        time: 5964,
        vues: 356000,
    },
    {
        rawTime: "3:02:04  ",
        rawVues: "1,1Mde",
        title: "Effondrement : notre civilisation au bord du gouffre ? Aurore Stéphant [EN DIRECT]",
        time: 10924,
        vues: 1100000,
    },
    {
        rawTime: "2:25:11  ",
        rawVues: "1Mde",
        title: "Les sols à l'agonie, peut-on encore les sauver ? Lydia et Claude Bourguignon [EN DIRECT]",
        time: 8711,
        vues: 1000000,
    },
    {
        rawTime: "1:21:33  ",
        rawVues: "459k",
        title: "EDF : Saccagé délibérément par l'Europe ? Henri Proglio [EN DIRECT]",
        time: 4893,
        vues: 459000,
    },
    {
        rawTime: "2:18:58  ",
        rawVues: "957k",
        title: "Souveraineté énergétique : vers une tiers-mondisation de la France ? Hervé Machenaud [EN DIRECT]",
        time: 8338,
        vues: 957000,
    },
    {
        rawTime: "2:02:00  ",
        rawVues: "451k",
        title: "[VF] Mégamenaces, un avenir sombre, des politiques dans le déni ? Nouriel Roubini [EN DIRECT]",
        time: 7320,
        vues: 451000,
    },
    {
        rawTime: "1:32:36  ",
        rawVues: "667k",
        title: "La fin de l'abondance industrielle ? Louis Gallois et Olivier Lluansi [EN DIRECT]",
        time: 5556,
        vues: 667000,
    },
    {
        rawTime: "2:06:50  ",
        rawVues: "493k",
        title: "Une formidable crise financière en perspective ? Jézabel Couppey-Soubeyran [EN DIRECT]",
        time: 7610,
        vues: 493000,
    },
    {
        rawTime: "2:25:11  ",
        rawVues: "981k",
        title: "Comment la France va-t-elle s’en sortir ? Loïk Le Floch-Prigent [EN DIRECT]",
        time: 8711,
        vues: 981000,
    },
    {
        rawTime: "2:26:17  ",
        rawVues: "669k",
        title: "En route vers un confinement énergétique ? Nicolas Meilhan et Philippe Bihouix [EN DIRECT]",
        time: 8777,
        vues: 669000,
    },
    {
        rawTime: "1:30:05  ",
        rawVues: "356k",
        title: "Les coulisses édifiantes des paradis fiscaux ? Renaud Van Ruymbeke [EN DIRECT]",
        time: 5405,
        vues: 356000,
    },
    {
        rawTime: "3:06:32  ",
        rawVues: "812k",
        title: "Crise financière, réchauffement climatique, où va l'Afrique ? Lionel Zinsou [EN DIRECT]",
        time: 11192,
        vues: 812000,
    },
    {
        rawTime: "2:19:25  ",
        rawVues: "762k",
        title: "En bande organisée ? Flore Vasseur [EN DIRECT]",
        time: 8365,
        vues: 762000,
    },
    {
        rawTime: "2:50:15  ",
        rawVues: "2,6Mde",
        title: "Crise financière: la descente aux enfers? Gaël Giraud, Raphaël Rossello & Gilles Raveaud [EN DIRECT]",
        time: 10215,
        vues: 2600000,
    },
    {
        rawTime: "1:51:49  ",
        rawVues: "528k",
        title: "La malbouffe contre-attaque ? Christophe Brusset [EN DIRECT]",
        time: 6709,
        vues: 528000,
    },
    {
        rawTime: "2:48:31  ",
        rawVues: "1,3Mde",
        title: "Où va la France ? François Ruffin [EN DIRECT]",
        time: 10111,
        vues: 1300000,
    },
    {
        rawTime: "1:43:17  ",
        rawVues: "272k",
        title: "Le chimpanzé qui murmurait à l'oreille de l'homme ? Frans de Waal [EN DIRECT]",
        time: 6197,
        vues: 272000,
    },
    {
        rawTime: "1:37:50  ",
        rawVues: "457k",
        title: "Faut-il accepter de négocier avec le diable ? Pierre Hazan [EN DIRECT]",
        time: 5870,
        vues: 457000,
    },
    {
        rawTime: "2:09:57  ",
        rawVues: "1,7Mde",
        title: "Anesthésie générale ? Jérémy Ferrari [EN DIRECT]",
        time: 7797,
        vues: 1700000,
    },
    {
        rawTime: "2:27:07  ",
        rawVues: "1,2Mde",
        title: "Nous sommes en guerre, la stratégie française ? Général Didier Castres [EN DIRECT]",
        time: 8827,
        vues: 1200000,
    },
    {
        rawTime: "1:39:23  ",
        rawVues: "895k",
        title: "Les bellicistes de plateaux TV, complexe militaro-intellectuel ? Pierre Conesa [EN DIRECT]",
        time: 5963,
        vues: 895000,
    },
    {
        rawTime: "2:35:59  ",
        rawVues: "699k",
        title: "Nucléaire : Choc énergétique, inflationniste, écologique ? Nicolas Nace & Gilles Babinet [EN DIRECT]",
        time: 9359,
        vues: 699000,
    },
    {
        rawTime: "3:01:00  ",
        rawVues: "5,8Mde",
        title: "Effondrement économique, monétaire & civilisationnel ? Charles Gave & Olivier Delamarche [EN DIRECT]",
        time: 10860,
        vues: 5800000,
    },
    {
        rawTime: "2:10:29  ",
        rawVues: "220k",
        title: "La science-fiction prédit la guerre ? August Cole [EN DIRECT]",
        time: 7829,
        vues: 220000,
    },
    {
        rawTime: "2:11:53  ",
        rawVues: "311k",
        title: "Perte de liberté et grogne sociale ? Michel Wieviorka [EN DIRECT]",
        time: 7913,
        vues: 311000,
    },
    {
        rawTime: "2:04:47  ",
        rawVues: "766k",
        title: "35 ans de DGSE, une pointe de diamant ? Alain Chouet [EN DIRECT]",
        time: 7487,
        vues: 766000,
    },
    {
        rawTime: "2:05:41  ",
        rawVues: "1Mde",
        title: "Crise de l'eau, planète terre invivable ? Emma Haziza [EN DIRECT]",
        time: 7541,
        vues: 1000000,
    },
    {
        rawTime: "2:05:34  ",
        rawVues: "746k",
        title: "Tempête géopolitique ? Pascal Boniface [EN DIRECT]",
        time: 7534,
        vues: 746000,
    },
    {
        rawTime: "1:43:14  ",
        rawVues: "316k",
        title: "Vivre en dictature ? Sacha Filipenko [EN DIRECT]",
        time: 6194,
        vues: 316000,
    },
    {
        rawTime: "2:07:24  ",
        rawVues: "707k",
        title: "L'Europe à court d'énergie ? Nicolas Meilhan et Francis Perrin [EN DIRECT]",
        time: 7644,
        vues: 707000,
    },
    {
        rawTime: "2:11:24  ",
        rawVues: "959k",
        title: "Où va la France ? Jean-Luc Mélenchon - Part 2 [EN DIRECT]",
        time: 7884,
        vues: 959000,
    },
    {
        rawTime: "2:30:39  ",
        rawVues: "337k",
        title: "Coup d'état numérique, la matrice ? Christophe Deloire [EN DIRECT]",
        time: 9039,
        vues: 337000,
    },
    {
        rawTime: "1:59:18  ",
        rawVues: "1,4Mde",
        title: "Comment arrive -t-on à la guerre ? Pierre Conesa [EN DIRECT]",
        time: 7158,
        vues: 1400000,
    },
    {
        rawTime: "1:50:26  ",
        rawVues: "488k",
        title: "Crash des médias ? Crash des journalistes ? Paul Moreira et Edwy Plenel [EN DIRECT]",
        time: 6626,
        vues: 488000,
    },
    {
        rawTime: "3:04:16  ",
        rawVues: "1,4Mde",
        title: "L'emprise, la France sous influence ? Marc Endeweld [EN DIRECT]",
        time: 11056,
        vues: 1400000,
    },
    {
        rawTime: "2:48:27  ",
        rawVues: "1,3Mde",
        title: "Éviter l’effondrement ? Jean-Marc Jancovici - Laurent Morel [EN DIRECT]",
        time: 10107,
        vues: 1300000,
    },
    {
        rawTime: "2:12:24  ",
        rawVues: "383k",
        title: "La France face à la nouvelle mondialisation ? Geoffroy Roux de Bézieux [EN DIRECT]",
        time: 7944,
        vues: 383000,
    },
    {
        rawTime: "3:12:02  ",
        rawVues: "2,2Mde",
        title: "L'effondrement : le point critique ? Aurore Stéphant [EN DIRECT]",
        time: 11522,
        vues: 2200000,
    },
    {
        rawTime: "2:12:55  ",
        rawVues: "1,5Mde",
        title: "Où va la France ? Jean-Luc Mélenchon - Part 1 [EN DIRECT]",
        time: 7975,
        vues: 1500000,
    },
    {
        rawTime: "2:06:28  ",
        rawVues: "548k",
        title: "L'art de la guerre et du commandement ? Loïc Finaz [EN DIRECT]",
        time: 7588,
        vues: 548000,
    },
    {
        rawTime: "1:19:09  ",
        rawVues: "829k",
        title: "Science et société, où va-t-on ? Étienne Klein [EN DIRECT]",
        time: 4749,
        vues: 829000,
    },
    {
        rawTime: "2:12:28  ",
        rawVues: "937k",
        title: "Militarisation de la langue ? Clément Viktorovitch [EN DIRECT]",
        time: 7948,
        vues: 937000,
    },
    {
        rawTime: "2:33:27  ",
        rawVues: "356k",
        title: "Désamorcer notre impuissance politique ? Eric Sadin [EN DIRECT]",
        time: 9207,
        vues: 356000,
    },
    {
        rawTime: "1:26:41  ",
        rawVues: "188k",
        title: "Julian Assange, torture made in Europe ? John Shipton [EN DIRECT]",
        time: 5201,
        vues: 188000,
    },
    {
        rawTime: "2:35:00  ",
        rawVues: "617k",
        title: "De la récession à la crypto ?  Raphaël Rossello et Owen Simonin [EN DIRECT]",
        time: 9300,
        vues: 617000,
    },
    {
        rawTime: "1:36:18  ",
        rawVues: "442k",
        title: "Réindustrialisation : reprendre son autonomie ? Anais Voy Gillis [EN DIRECT]",
        time: 5778,
        vues: 442000,
    },
    {
        rawTime: "1:36:15  ",
        rawVues: "2,5Mde",
        title: "Où va la France ? Eric Zemmour [EN DIRECT]",
        time: 5775,
        vues: 2500000,
    },
    {
        rawTime: "2:40:16  ",
        rawVues: "251k",
        title: "Journaliste sous les balles ? Régis Le Sommier [EN DIRECT]",
        time: 9616,
        vues: 251000,
    },
    {
        rawTime: "1:54:24  ",
        rawVues: "655k",
        title: "La Finance destructrice de démocratie ? Georges Ugeux [EN DIRECT]",
        time: 6864,
        vues: 655000,
    },
    {
        rawTime: "2:39:32  ",
        rawVues: "677k",
        title: "Le hacking au XXIe siècle ? Zax et Doomer [EN DIRECT]",
        time: 9572,
        vues: 677000,
    },
    {
        rawTime: "3:29:35  ",
        rawVues: "2,6Mde",
        title: "Ambassadeur de Chine sans filtre ? Lu Shaye [EN DIRECT]",
        time: 12575,
        vues: 2600000,
    },
    {
        rawTime: "1:57:26  ",
        rawVues: "1Mde",
        title: "La fin de la guerre classique ? Alain Juillet [EN DIRECT]",
        time: 7046,
        vues: 1000000,
    },
    {
        rawTime: "2:19:12  ",
        rawVues: "997k",
        title: "Le rapport qui annonce l'apocalypse ? Valérie Masson-Delmotte et Pierre Larrouturou  [EN DIRECT]",
        time: 8352,
        vues: 997000,
    },
    {
        rawTime: "1:54:36  ",
        rawVues: "696k",
        title: "Pas de prison pour les grands escrocs ? Renaud Van Ruymbeke [EN DIRECT]",
        time: 6876,
        vues: 696000,
    },
    {
        rawTime: "1:55:59  ",
        rawVues: "308k",
        title: "66% d'abstention : la grande confusion ? Philippe Corcuff [EN DIRECT]",
        time: 6959,
        vues: 308000,
    },
    {
        rawTime: "2:09:00  ",
        rawVues: "835k",
        title: "Pass sanitaire, géopolitique de la Data, copie privée ? Benjamin Bayart et Marc Rees [EN DIRECT]",
        time: 7740,
        vues: 835000,
    },
    {
        rawTime: "1:44:27  ",
        rawVues: "364k",
        title: "La satire avant la guerre ? Bruno Gaccio [EN DIRECT]",
        time: 6267,
        vues: 364000,
    },
    {
        rawTime: "2:31:53  ",
        rawVues: "672k",
        title: "Militaires en colère ? Henri Bentégeat [EN DIRECT]",
        time: 9113,
        vues: 672000,
    },
    {
        rawTime: "2:58:06  ",
        rawVues: "2,2Mde",
        title: "Géopolitique : Le désastre Français ? Hubert Védrine [EN DIRECT]",
        time: 10686,
        vues: 2200000,
    },
    {
        rawTime: "3:32:30  ",
        rawVues: "3,1Mde",
        title: "Philippe de Villiers sans filtre ? [EN DIRECT]",
        time: 12750,
        vues: 3100000,
    },
    {
        rawTime: "2:00:42  ",
        rawVues: "411k",
        title: "Au cœur des soulèvements ? Gaspard Glanz [EN DIRECT]",
        time: 7242,
        vues: 411000,
    },
    {
        rawTime: "2:20:30  ",
        rawVues: "647k",
        title: "Démocratie : Épiphénomène historique, sécession des élites ? Barbara Stiegler [EN DIRECT]",
        time: 8430,
        vues: 647000,
    },
    {
        rawTime: "1:41:44  ",
        rawVues: "531k",
        title: "Covid : aux origines du mal ? Brice Perrier [EN DIRECT]",
        time: 6104,
        vues: 531000,
    },
    {
        rawTime: "2:19:57  ",
        rawVues: "902k",
        title: "Les radicalismes religieux et le Lobby Saoudien en France ? Pierre Conesa [EN DIRECT]",
        time: 8397,
        vues: 902000,
    },
    {
        rawTime: "2:23:27  ",
        rawVues: "659k",
        title: "Désinformation en temps d'épidémie ? Pr Renaud Piarroux [EN DIRECT]",
        time: 8607,
        vues: 659000,
    },
    {
        rawTime: "2:28:40  ",
        rawVues: "2,2Mde",
        title: "Crise gigantesque en approche ? Gilles Raveaud [ EN DIRECT ]",
        time: 8920,
        vues: 2200000,
    },
    {
        rawTime: "2:03:47  ",
        rawVues: "553k",
        title: "France : Corruption à tous les étages ? Elise Van Beneden, Anticor[ EN DIRECT ]",
        time: 7427,
        vues: 553000,
    },
    {
        rawTime: "1:46:13  ",
        rawVues: "473k",
        title: "Guillaume Meurice : Le bouffon du Roi ? [ EN DIRECT ]",
        time: 6373,
        vues: 473000,
    },
    {
        rawTime: "2:20:10  ",
        rawVues: "744k",
        title: "Banquier d'affaires face aux crises ? Raphaël Rossello [ EN DIRECT ]",
        time: 8410,
        vues: 744000,
    },
    {
        rawTime: "2:31:48  ",
        rawVues: "347k",
        title: "La France en cours de tiers-mondisation ? Yves Jégo  [ EN DIRECT ]",
        time: 9108,
        vues: 347000,
    },
    {
        rawTime: "1:50:43  ",
        rawVues: "328k",
        title: "50 ans d'Utopie ? Yann Arthus-Bertrand  [ EN DIRECT ]",
        time: 6643,
        vues: 328000,
    },
    {
        rawTime: "2:50:28  ",
        rawVues: "877k",
        title: "COVID 19 : La faillite occidentale ? Renaud Piarroux [ EN DIRECT ]",
        time: 10228,
        vues: 877000,
    },
    {
        rawTime: "2:55:04  ",
        rawVues: "652k",
        title: "En route vers la dictature ? Christophe Deloire [EN DIRECT]",
        time: 10504,
        vues: 652000,
    },
    {
        rawTime: "2:29:20  ",
        rawVues: "313k",
        title: "La Justice face aux Politiques, aux terroristes ? Béatrice Brugère [EN DIRECT]",
        time: 8960,
        vues: 313000,
    },
    {
        rawTime: "1:55:23  ",
        rawVues: "378k",
        title: "Partout où nécessité fait loi ? Cédric Herrou",
        time: 6923,
        vues: 378000,
    },
    {
        rawTime: "2:48:51  ",
        rawVues: "2,1Mde",
        title: "La police en déconfiture ? Alexandre Langlois et Noam Anouar [ En direct ]",
        time: 10131,
        vues: 2100000,
    },
    {
        rawTime: "2:01:22  ",
        rawVues: "482k",
        title: "Journalisme de façade, de cour, de trottoir ? Julia Cagé [ En direct ]",
        time: 7282,
        vues: 482000,
    },
    {
        rawTime: "2:32:32  ",
        rawVues: "1,4Mde",
        title: "L'espion qui nous veut du bien ? Marc Eichinger [ En direct ]",
        time: 9152,
        vues: 1400000,
    },
    {
        rawTime: "1:34:46  ",
        rawVues: "488k",
        title: "France : réveiller nos vieux démons ? Arnaud Montebourg [ En direct ]",
        time: 5686,
        vues: 488000,
    },
    {
        rawTime: "1:52:03  ",
        rawVues: "442k",
        title: "Le Covid, les fake news, les journalistes ? Noël Mamère [ En direct ]",
        time: 6723,
        vues: 442000,
    },
    {
        rawTime: "2:44:42  ",
        rawVues: "409k",
        title: "L'État démissionnaire ? Anne-Laure Kiechel [ En direct ]",
        time: 9882,
        vues: 409000,
    },
    {
        rawTime: "2:02:12  ",
        rawVues: "586k",
        title: "Nager avec les requins ? Denis Robert [ En direct ]",
        time: 7332,
        vues: 586000,
    },
    {
        rawTime: "1:33:18  ",
        rawVues: "567k",
        title: "Le futur, entre 5G et Amish ? Nicolas Meilhan et Philippe Bihouix [EN DIRECT]",
        time: 5598,
        vues: 567000,
    },
    {
        rawTime: "1:39:27  ",
        rawVues: "2,5Mde",
        title: "Adieu les cons, transhumance suicidaire ? Albert Dupontel [EN DIRECT]",
        time: 5967,
        vues: 2500000,
    },
    {
        rawTime: "3:03:40  ",
        rawVues: "883k",
        title: "La fin d’un monde commun ? Éric Sadin [EN DIRECT]",
        time: 11020,
        vues: 883000,
    },
    {
        rawTime: "2:00:42  ",
        rawVues: "1,4Mde",
        title: "Chaos économique, blanchiment bancaire ? Gaël Giraud [EN DIRECT]",
        time: 7242,
        vues: 1400000,
    },
    {
        rawTime: "1:28:50  ",
        rawVues: "386k",
        title: "Les sangsues de la République ? Isabelle Saporta [EN DIRECT]",
        time: 5330,
        vues: 386000,
    },
    {
        rawTime: "2:06:32  ",
        rawVues: "551k",
        title: "Crise économique, débats interdits en France ? Jean-Paul Fitoussi [EN DIRECT]",
        time: 7592,
        vues: 551000,
    },
    {
        rawTime: "2:18:49  ",
        rawVues: "479k",
        title: "Souveraineté numérique, la douche froide ? Tariq Krim et Bernard Benhamou [EN DIRECT]",
        time: 8329,
        vues: 479000,
    },
    {
        rawTime: "2:28:33  ",
        rawVues: "3,3Mde",
        title: "Où en est la France ? Michel Onfray [EN DIRECT]",
        time: 8913,
        vues: 3300000,
    },
    {
        rawTime: "2:14:58  ",
        rawVues: "1,3Mde",
        title: "L'espion, le Covid et le truand ? Maxime Renahy [EN DIRECT]",
        time: 8098,
        vues: 1300000,
    },
    {
        rawTime: "1:44:13  ",
        rawVues: "796k",
        title: "Économie sous perfusion, les risques ? Olivier Delamarche [EN DIRECT]",
        time: 6253,
        vues: 796000,
    },
    {
        rawTime: "2:23:08  ",
        rawVues: "308k",
        title: "Solidité du système financier et des retraites ? F.X. Selleret et P. Sabatier [EN DIRECT]",
        time: 8588,
        vues: 308000,
    },
    {
        rawTime: "1:48:34  ",
        rawVues: "361k",
        title: "Choc économique : Perspectives alternatives ? Isabelle Delannoy [EN DIRECT]",
        time: 6514,
        vues: 361000,
    },
    {
        rawTime: "2:01:51  ",
        rawVues: "315k",
        title: "Un monde malade : quelles sont les pistes ? DataGueule [EN DIRECT]",
        time: 7311,
        vues: 315000,
    },
    {
        rawTime: "2:47:56  ",
        rawVues: "460k",
        title: "COVID-19, panique sociale, scientifique et politique ? Philippe Douste-Blazy [EN DIRECT]",
        time: 10076,
        vues: 460000,
    },
    {
        rawTime: "2:20:35  ",
        rawVues: "638k",
        title: "COVID-19, Crise financière, Chine, Menace sur la France. Christian Harbulot [EN DIRECT]",
        time: 8435,
        vues: 638000,
    },
    {
        rawTime: "2:32:01  ",
        rawVues: "957k",
        title: "Insurrections, Espions, COVID-19, Crise mondiales. Bernard Squarcini [EN DIRECT]",
        time: 9121,
        vues: 957000,
    },
    {
        rawTime: "1:34:54  ",
        rawVues: "215k",
        title: "Migrants/Réfugiés, le grand scandale ? Jean Ziegler [EN DIRECT]",
        time: 5694,
        vues: 215000,
    },
    {
        rawTime: "1:46:22  ",
        rawVues: "142k",
        title: "[ VO ] Collapsologie, anxiété et dépression ? Glenn Albrecht [EN DIRECT]",
        time: 6382,
        vues: 142000,
    },
    {
        rawTime: "1:38:30  ",
        rawVues: "360k",
        title: "Général 5 étoiles face à la bombe nucléaire ? Bernard Norlain [EN DIRECT]",
        time: 5910,
        vues: 360000,
    },
    {
        rawTime: "2:08:54  ",
        rawVues: "597k",
        title: "Les politiques, l'important c'est pas la chute ? Virginie Martin [EN DIRECT]",
        time: 7734,
        vues: 597000,
    },
    {
        rawTime: "2:03:55  ",
        rawVues: "355k",
        title: "La religion de la croissance économique? Delphine Batho [EN DIRECT]",
        time: 7435,
        vues: 355000,
    },
    {
        rawTime: "1:29:12  ",
        rawVues: "288k",
        title: "Radars : un pognon de dingue ? Reflets + Extra-Muros [EN DIRECT]",
        time: 5352,
        vues: 288000,
    },
    {
        rawTime: "1:39:03  ",
        rawVues: "731k",
        title: "Humour, pensée formatée et politiquement correct ? Thomas Wiesel [EN DIRECT]",
        time: 5943,
        vues: 731000,
    },
    {
        rawTime: "2:43:52  ",
        rawVues: "1,7Mde",
        title: "Macron : les réseaux secrets ? Marc Endeweld [EN DIRECT]",
        time: 9832,
        vues: 1700000,
    },
    {
        rawTime: "1:30:47  ",
        rawVues: "867k",
        title: "L'enfumage de la transition écologique ? Guillaume Pitron [EN DIRECT]",
        time: 5447,
        vues: 867000,
    },
    {
        rawTime: "2:11:11  ",
        rawVues: "286k",
        title: "Guerre économique, surveillance de masse ? Cédric O [EN DIRECT]",
        time: 7871,
        vues: 286000,
    },
    {
        rawTime: "2:31:38  ",
        rawVues: "508k",
        title: "Propagande et contre-propagande ? Christophe Stalla-Bourdillon [EN DIRECT]",
        time: 9098,
        vues: 508000,
    },
    {
        rawTime: "2:28:50  ",
        rawVues: "410k",
        title: "Crise de la masculinité ? Francis Dupuis-Déri [EN DIRECT]",
        time: 8930,
        vues: 410000,
    },
    {
        rawTime: "2:08:05  ",
        rawVues: "314k",
        title: "Camisole numérique pour votre bien ? Gilles Babinet [EN DIRECT]",
        time: 7685,
        vues: 314000,
    },
    {
        rawTime: "3:04:40  ",
        rawVues: "4Mde",
        title: "L’agroalimentaire vu de l’intérieur, intoxication ? Christophe Brusset [EN DIRECT]",
        time: 11080,
        vues: 4000000,
    },
    {
        rawTime: "1:09:16  ",
        rawVues: "212k",
        title: "Europe, dictature technocratique ? Costa-Gavras [EN DIRECT]",
        time: 4156,
        vues: 212000,
    },
    {
        rawTime: "2:20:47  ",
        rawVues: "724k",
        title: "Clientélisme politique et Moyen-Orient : Agnès Levallois et Pierre Conesa [EN DIRECT]",
        time: 8447,
        vues: 724000,
    },
    {
        rawTime: "2:07:49  ",
        rawVues: "1,2Mde",
        title: "Médias, les nouveaux GUIGNOLS ? Bruno Gaccio [EN DIRECT]",
        time: 7669,
        vues: 1200000,
    },
    {
        rawTime: "2:31:12  ",
        rawVues: "862k",
        title: "L'explosion des banques ? Christophe Nijdam & Jérôme Cazes [EN DIRECT]",
        time: 9072,
        vues: 862000,
    },
    {
        rawTime: "1:23:09  ",
        rawVues: "378k",
        title: "GIEC : Le climat survivra-t-il au capitalisme ? Jouzel & Larrouturou [EN DIRECT]",
        time: 4989,
        vues: 378000,
    },
    {
        rawTime: "2:03:18  ",
        rawVues: "318k",
        title: "Un prix Nobel face au krach à venir ? Joseph Stiglitz [EN DIRECT]",
        time: 7398,
        vues: 318000,
    },
    {
        rawTime: "2:21:14  ",
        rawVues: "858k",
        title: "DGSE : Face à la réalité ? Talk with a spy [EN DIRECT]",
        time: 8474,
        vues: 858000,
    },
    {
        rawTime: "2:29:10  ",
        rawVues: "442k",
        title: "Guerre économique sans pitié pour la France ? Olivier Marleix [EN DIRECT]",
        time: 8950,
        vues: 442000,
    },
    {
        rawTime: "1:33:36  ",
        rawVues: "522k",
        title: "La France en danger: où en est le renseignement ? Eric Dénécé [EN DIRECT]",
        time: 5616,
        vues: 522000,
    },
    {
        rawTime: "1:57:21  ",
        rawVues: "368k",
        title: "Football : du pain, des jeux et des magouilles ? Vikash Dhorasoo [EN DIRECT]",
        time: 7041,
        vues: 368000,
    },
    {
        rawTime: "1:42:58  ",
        rawVues: "524k",
        title: "DGSE : l'impuissance de l'état ? Maxime Renahy [ EN DIRECT ]",
        time: 6178,
        vues: 524000,
    },
    {
        rawTime: "1:45:11  ",
        rawVues: "941k",
        title: "USA : Nos anciens alliés ? Arnaud Montebourg [EN DIRECT]",
        time: 6311,
        vues: 941000,
    },
    {
        rawTime: "2:14:49  ",
        rawVues: "3Mde",
        title: "Alstom : la France vendue à la découpe ? Frédéric Pierucci [EN DIRECT]",
        time: 8089,
        vues: 3000000,
    },
    {
        rawTime: "1:20:41  ",
        rawVues: "1,1Mde",
        title: "Arabie Saoudite, un pays protégé ? Pierre Conesa [EN DIRECT]",
        time: 4841,
        vues: 1100000,
    },
    {
        rawTime: "1:22:42  ",
        rawVues: "531k",
        title: "Ecologie, Transport et Mythomanie : Laurent Castaignède [EN DIRECT]",
        time: 4962,
        vues: 531000,
    },
    {
        rawTime: "1:43:58  ",
        rawVues: "616k",
        title: "Débat : L'avenir de l'humanité ? Laurent Alexandre et Philippe Bihouix [EN DIRECT]",
        time: 6238,
        vues: 616000,
    },
    {
        rawTime: "1:59:41  ",
        rawVues: "294k",
        title: "Laherrère, Meilhan: Croissance, énergie, le point de non-retour ? [EN DIRECT]",
        time: 7181,
        vues: 294000,
    },
    {
        rawTime: "2:12:59  ",
        rawVues: "886k",
        title: "Jean Ziegler : Pourquoi il faut détruire le capitalisme ? [EN DIRECT]",
        time: 7979,
        vues: 886000,
    },
    {
        rawTime: "1:53:01  ",
        rawVues: "215k",
        title: "Alain Grandjean : la finance va-t-elle sauver la planète ? [EN DIRECT]",
        time: 6781,
        vues: 215000,
    },
    {
        rawTime: "1:30:31  ",
        rawVues: "1,6Mde",
        title: "Monique Pinçon-Charlot : Casse sociale, le début ? [EN DIRECT]",
        time: 5431,
        vues: 1600000,
    },
    {
        rawTime: "1:31:48  ",
        rawVues: "910k",
        title: "Mediapart : Benalla, Macron, le journalisme menacé ?  [EN DIRECT]",
        time: 5508,
        vues: 910000,
    },
    {
        rawTime: "1:24:55  ",
        rawVues: "797k",
        title: "Barbara Stiegler : S'adapter à une société malade ? [EN DIRECT]",
        time: 5095,
        vues: 797000,
    },
    {
        rawTime: "1:43:32  ",
        rawVues: "539k",
        title: "Philippe Bihouix : Prophète de l’apocalypse ? [EN DIRECT]",
        time: 6212,
        vues: 539000,
    },
    {
        rawTime: "1:18:34  ",
        rawVues: "357k",
        title: "Union Européenne pour ou contre ? Coralie Delaume [EN DIRECT]",
        time: 4714,
        vues: 357000,
    },
    {
        rawTime: "2:41:08  ",
        rawVues: "2,3Mde",
        title: "Jean-Luc Mélenchon : face à la réalité ? [EN DIRECT]",
        time: 9668,
        vues: 2300000,
    },
    {
        rawTime: "1:30:55  ",
        rawVues: "444k",
        title: "Bernard Stiegler : Etat d'urgence, géopolitique, Médias, Gilets Jaunes [EN DIRECT]",
        time: 5455,
        vues: 444000,
    },
    {
        rawTime: "1:37:11  ",
        rawVues: "176k",
        title: "Champagne, Duplessy et Fontaine : Investigation sans filtre ? [EN DIRECT]",
        time: 5831,
        vues: 176000,
    },
    {
        rawTime: "1:38:55  ",
        rawVues: "298k",
        title: "Charles Rojzman : Vers les Guerres civiles ? [EN DIRECT]",
        time: 5935,
        vues: 298000,
    },
    {
        rawTime: "1:41:20  ",
        rawVues: "622k",
        title: "Alain Damasio : l'intuition de la science-fiction ? [EN DIRECT]",
        time: 6080,
        vues: 622000,
    },
    {
        rawTime: "1:46:04  ",
        rawVues: "279k",
        title: "Géopolitique : Cynisme et bons sentiments ? Caroline Galacteros [EN DIRECT]",
        time: 6364,
        vues: 279000,
    },
    {
        rawTime: "1:59:30  ",
        rawVues: "626k",
        title: "Noam Anouar : Lucidité face aux terrorismes ?  [EN DIRECT]",
        time: 7170,
        vues: 626000,
    },
    {
        rawTime: "1:36:14  ",
        rawVues: "2,3Mde",
        title: "Gaël Giraud : Tsunami financier, désastre humanitaire ? [EN DIRECT]",
        time: 5774,
        vues: 2300000,
    },
    {
        rawTime: "2:04:52  ",
        rawVues: "4,9Mde",
        title: "L'illusion de la démocratie en France ? Juan Branco [EN DIRECT]",
        time: 7492,
        vues: 4900000,
    },
    {
        rawTime: "1:36:17  ",
        rawVues: "380k",
        title: "Société à bout de souffle ? Aymeric Caron [EN DIRECT]",
        time: 5777,
        vues: 380000,
    },
    {
        rawTime: "2:12:15  ",
        rawVues: "700k",
        title: "Démocratie : Marketing politique pour les pauvres? Francis Dupuis-Déri [EN DIRECT]",
        time: 7935,
        vues: 700000,
    },
    {
        rawTime: "1:46:52  ",
        rawVues: "696k",
        title: "Gilets Jaunes : Avant la révolution ? François Boulo [EN DIRECT]",
        time: 6412,
        vues: 696000,
    },
    {
        rawTime: "1:25:42  ",
        rawVues: "934k",
        title: "François Bégaudeau : Gilets Jaunes, Populisme, Bourgeois ? [EN DIRECT]",
        time: 5142,
        vues: 934000,
    },
    {
        rawTime: "46:11  ",
        rawVues: "69k",
        title: "Khalid Essa: Taxi un métier en danger ? [EN DIRECT]",
        time: 2771,
        vues: 69000,
    },
    {
        rawTime: "2:02:49  ",
        rawVues: "208k",
        title: "Yánis Varoufákis, la fin de l'Europe et de l'Euro ? [EN DIRECT]",
        time: 7369,
        vues: 208000,
    },
    {
        rawTime: "2:08:35  ",
        rawVues: "1,2Mde",
        title: "Jean-Marc Jancovici et Philippe Bihouix : Croissance et Effondrement [EN DIRECT]",
        time: 7715,
        vues: 1200000,
    },
    {
        rawTime: "1:00:30  ",
        rawVues: "366k",
        title: "Natacha Polony : Journalisme et #LigueduLOL [EN DIRECT]",
        time: 3630,
        vues: 366000,
    },
    {
        rawTime: "1:14:43  ",
        rawVues: "748k",
        title: "Alexandre Langlois : Violences policières et Gilets Jaunes [EN DIRECT]",
        time: 4483,
        vues: 748000,
    },
    {
        rawTime: "1:20:37  ",
        rawVues: "261k",
        title: "Vincent Cespedes : Gilets Jaunes : Comprendre la violence ? [EN DIRECT]",
        time: 4837,
        vues: 261000,
    },
    {
        rawTime: "1:24:58  ",
        rawVues: "165k",
        title: "Aminata Dramane Traoré : Afrique, Gilets Jaunes depuis 150 ans ? [EN DIRECT]",
        time: 5098,
        vues: 165000,
    },
    {
        rawTime: "1:20:30  ",
        rawVues: "535k",
        title: "Les milliardaires gavés au sang des gilets jaunes ? Denis Robert [EN DIRECT]",
        time: 4830,
        vues: 535000,
    },
    {
        rawTime: "2:14:13  ",
        rawVues: "1,1Mde",
        title: "Jacques Sapir, Olivier Berruyer et Olivier Delamarche : Gilets Jaunes, début de la fin pour l'UE ?",
        time: 8053,
        vues: 1100000,
    },
    {
        rawTime: "1:40:54  ",
        rawVues: "598k",
        title: "Alekseï Pouchkov : Futur de l'ordre mondial, la menace russe ? [EN DIRECT]",
        time: 6054,
        vues: 598000,
    },
    {
        rawTime: "1:04:33  ",
        rawVues: "293k",
        title: "Corruption, : Maladie de la France ?Jean-Christophe Picard, Anticor sans filtre [EN DIRECT]",
        time: 3873,
        vues: 293000,
    },
    {
        rawTime: "1:06:36  ",
        rawVues: "176k",
        title: "Une Justice sous Macron ? Carbon de Seze [EN DIRECT]",
        time: 3996,
        vues: 176000,
    },
    {
        rawTime: "1:32:29  ",
        rawVues: "711k",
        title: "Jérémy Ferrari : la révolte par l'humour ? [EN DIRECT]",
        time: 5549,
        vues: 711000,
    },
    {
        rawTime: "1:50:10  ",
        rawVues: "307k",
        title: "Armée française : Quelle stratégie ? Général Vincent Desportes [EN DIRECT]",
        time: 6610,
        vues: 307000,
    },
    {
        rawTime: "1:57:03  ",
        rawVues: "2,4Mde",
        title: "Kémi Séba : Panafricanisme 2.0 ? [EN DIRECT]",
        time: 7023,
        vues: 2400000,
    },
    {
        rawTime: "1:58:25  ",
        rawVues: "124k",
        title: "Migrants / Réfugiés / Immigration : problèmes inextricables ? Frédéric Penard [EN DIRECT]",
        time: 7105,
        vues: 124000,
    },
    {
        rawTime: "1:36:42  ",
        rawVues: "338k",
        title: "Autopsie du Journalisme, de Hitler à Trump : Daniel Schneidermann [EN DIRECT]",
        time: 5802,
        vues: 338000,
    },
    {
        rawTime: "2:19:59  ",
        rawVues: "697k",
        title: "Éric Sadin : l'asservissement par l'Intelligence Artificielle ? [EN DIRECT]",
        time: 8399,
        vues: 697000,
    },
    {
        rawTime: "2:13:51  ",
        rawVues: "1,6Mde",
        title: "Emmanuel Todd : Trahison des élites françaises ? [EN DIRECT]",
        time: 8031,
        vues: 1600000,
    },
    {
        rawTime: "1:35:56  ",
        rawVues: "1,2Mde",
        title: "La France interdite ? Laurent Obertone [EN DIRECT]",
        time: 5756,
        vues: 1200000,
    },
    {
        rawTime: "2:10:25  ",
        rawVues: "268k",
        title: "Terrorisme ou Légitime défense ? Thibault de Montbrial [EN DIRECT]",
        time: 7825,
        vues: 268000,
    },
    {
        rawTime: "1:26:24  ",
        rawVues: "341k",
        title: "Jérémie Zimmermann : 1984, un manuel d'instructions ? [EN DIRECT]",
        time: 5184,
        vues: 341000,
    },
    {
        rawTime: "1:38:30  ",
        rawVues: "457k",
        title: "P. Servigne & J. Blamont : Introduction au siècle des menaces [EN DIRECT]",
        time: 5910,
        vues: 457000,
    },
    {
        rawTime: "1:54:31  ",
        rawVues: "444k",
        title: "Anarchie VS Capitalisme ? Tancrède Ramonet EN DIRECT]",
        time: 6871,
        vues: 444000,
    },
    {
        rawTime: "1:59:43  ",
        rawVues: "406k",
        title: "École de Guerre : L’état du monde. Olivier Delamarche, Pierre Sabatier et Alain Juillet [EN DIRECT]",
        time: 7183,
        vues: 406000,
    },
    {
        rawTime: "1:58:49  ",
        rawVues: "180k",
        title: "Ambassade de Russie : Acte 2, Espions, Guerre Froide sans filtre [EN DIRECT]",
        time: 7129,
        vues: 180000,
    },
    {
        rawTime: "1:26:33  ",
        rawVues: "165k",
        title: "Ex-députée écolo : sans langue de bois ? Isabelle Attard [EN DIRECT]",
        time: 5193,
        vues: 165000,
    },
    {
        rawTime: "1:11:02  ",
        rawVues: "456k",
        title: "Edgar Morin : L’effondrement ? [EN DIRECT]",
        time: 4262,
        vues: 456000,
    },
    {
        rawTime: "1:21:58  ",
        rawVues: "91k",
        title: "Greenpeace : Menaces Nucléaire ? Yannick Rousselet [EN DIRECT]",
        time: 4918,
        vues: 91000,
    },
    {
        rawTime: "1:25:29  ",
        rawVues: "491k",
        title: "Pierre Conesa : Guerres, Embargos et Propagandes [EN DIRECT]",
        time: 5129,
        vues: 491000,
    },
    {
        rawTime: "1:38:48  ",
        rawVues: "2,1Mde",
        title: "Quand la Science appelle à l'aide pour l'humanité ? Aurélien Barrau [EN DIRECT]",
        time: 5928,
        vues: 2100000,
    },
    {
        rawTime: "1:22:41  ",
        rawVues: "229k",
        title: "Sankara, Françafrique, CFA, où va l'Afrique ? Louis Magloire Keumayou [EN DIRECT]",
        time: 4961,
        vues: 229000,
    },
    {
        rawTime: "1:36:13  ",
        rawVues: "458k",
        title: "Climat : Trois quarts de l'humanité menacés de mort ? Pierre Larrouturou [EN DIRECT]",
        time: 5773,
        vues: 458000,
    },
    {
        rawTime: "1:40:26  ",
        rawVues: "239k",
        title: "Surveillance, Hacker et Journaliste. Antoine Champagne et Olivier Laurelli Aka Bluetouff [EN DIRECT]",
        time: 6026,
        vues: 239000,
    },
    {
        rawTime: "2:15:52  ",
        rawVues: "222k",
        title: "Économie en danger ? Flux migratoires, Brexit et Mondialisation. M. Bruyère, E. Berr et D. Cayla",
        time: 8152,
        vues: 222000,
    },
    {
        rawTime: "1:42:25  ",
        rawVues: "169k",
        title: "Blockchain, gouvernance et énergie ? Primavera De Filippi et Remy Bourganel [EN DIRECT]",
        time: 6145,
        vues: 169000,
    },
    {
        rawTime: "2:04:59  ",
        rawVues: "187k",
        title: "Non Violence VS Urgence Climatique : Jon Palais [EN DIRECT]",
        time: 7499,
        vues: 187000,
    },
    {
        rawTime: "2:01:56  ",
        rawVues: "1,6Mde",
        title: "Jean-Pierre Petit : Modèle Janus et Armes russes [EN DIRECT]",
        time: 7316,
        vues: 1600000,
    },
    {
        rawTime: "1:58:02  ",
        rawVues: "553k",
        title: "François Ruffin, sans filtre : Journaliste VS Politique ? [EN DIRECT]",
        time: 7082,
        vues: 553000,
    },
    {
        rawTime: "1:10:20  ",
        rawVues: "445k",
        title: "Gunter Pauli : Biomimétisme et économie bleue [EN DIRECT]",
        time: 4220,
        vues: 445000,
    },
    {
        rawTime: "1:11:07  ",
        rawVues: "2,1Mde",
        title: "Étienne Klein : la structure fondamentale de la matière : le boson de higgs [EN DIRECT]",
        time: 4267,
        vues: 2100000,
    },
    {
        rawTime: "1:59:58  ",
        rawVues: "1,6Mde",
        title: "Sarkozy, corruption, assassinat et affaire d'état ? Fabrice Arfi (Mediapart) [EN DIRECT]",
        time: 7198,
        vues: 1600000,
    },
    {
        rawTime: "1:24:26  ",
        rawVues: "283k",
        title: "Survivre au système éducatif, Hackers et Crapauds fous. Thanh Nghiem [EN DIRECT]",
        time: 5066,
        vues: 283000,
    },
    {
        rawTime: "1:16:37  ",
        rawVues: "311k",
        title: "Le langage au service des puissants ? Alain Deneault [EN DIRECT]",
        time: 4597,
        vues: 311000,
    },
    {
        rawTime: "1:39:32  ",
        rawVues: "206k",
        title: "Criminalisation de la lutte sociale ? Jérémie Assous : Affaire Tarnac [EN DIRECT]",
        time: 5972,
        vues: 206000,
    },
    {
        rawTime: "1:46:15  ",
        rawVues: "951k",
        title: "Pierre Conesa : Propagande de Guerre, Cinéma, Géopolitique, Opinion publique [EN DIRECT]",
        time: 6375,
        vues: 951000,
    },
    {
        rawTime: "2:05:09  ",
        rawVues: "361k",
        title: "Ambassade de Russie, Espions, Guerre Froide sans filtre [EN DIRECT]",
        time: 7509,
        vues: 361000,
    },
    {
        rawTime: "2:21:12  ",
        rawVues: "2,8Mde",
        title: "DGSE, Espions, Secrets des Affaires, Crises mondiales. Alain Juillet [EN DIRECT]",
        time: 8472,
        vues: 2800000,
    },
    {
        rawTime: "2:21:28  ",
        rawVues: "1,1Mde",
        title: "Delamarche, Gave, Sabatier : Géopolitique, macroéconomie sans filtre [EN DIRECT]",
        time: 8488,
        vues: 1100000,
    },
    {
        rawTime: "1:54:33  ",
        rawVues: "289k",
        title: "Big Brother habite Place Beauvau ? Exégèse en libertés [EN DIRECT]",
        time: 6873,
        vues: 289000,
    },
    {
        rawTime: "1:18:34  ",
        rawVues: "204k",
        title: "Santé VS Nourriture ? Isabelle Saporta [EN DIRECT]",
        time: 4714,
        vues: 204000,
    },
    {
        rawTime: "1:32:24  ",
        rawVues: "548k",
        title: "Bernard Friot : Théorie du revenu universel / salaire à la qualification ? [EN DIRECT]",
        time: 5544,
        vues: 548000,
    },
    {
        rawTime: "1:53:40  ",
        rawVues: "391k",
        title: "Natacha Polony : Journalistes et médias sous contrôles ? [EN DIRECT]",
        time: 6820,
        vues: 391000,
    },
    {
        rawTime: "1:24:27  ",
        rawVues: "270k",
        title: "Aude Lancelin : Indépendance des médias ? [EN DIRECT]",
        time: 5067,
        vues: 270000,
    },
    {
        rawTime: "1:51:27  ",
        rawVues: "1,7Mde",
        title: "Effondrement de la civilisation ? Pablo Servigne [EN DIRECT]",
        time: 6687,
        vues: 1700000,
    },
    {
        rawTime: "56:58  ",
        rawVues: "109k",
        title: "Lord Esperanza : Rap nouvelle génération ? [EN DIRECT]",
        time: 3418,
        vues: 109000,
    },
    {
        rawTime: "1:14:17  ",
        rawVues: "3,8Mde",
        title: "Idriss Aberkane sans filtre [EN DIRECT]",
        time: 4457,
        vues: 3800000,
    },
    {
        rawTime: "1:21:04  ",
        rawVues: "82k",
        title: "Journalistes et liberté d'expression en danger ? [EN DIRECT]",
        time: 4864,
        vues: 82000,
    },
    {
        rawTime: "1:35:59  ",
        rawVues: "189k",
        title: "La police au service du marché ? Mathieu Rigouste [EN DIRECT]",
        time: 5759,
        vues: 189000,
    },
    {
        rawTime: "1:04:41  ",
        rawVues: "824k",
        title: "Étienne Klein : Éthique et philosophie des sciences, le rôle des scientifiques ? [EN DIRECT]",
        time: 3881,
        vues: 824000,
    },
    {
        rawTime: "1:14:41  ",
        rawVues: "449k",
        title: "Bernard Stiegler : mutations sociales, politiques, économiques et psychologiques [EN DIRECT]",
        time: 4481,
        vues: 449000,
    },
    {
        rawTime: "1:34:33  ",
        rawVues: "149k",
        title: "Propagande VS Journalisme ? RT France, Xenia Fedorova [EN DIRECT]",
        time: 5673,
        vues: 149000,
    },
    {
        rawTime: "1:50:51  ",
        rawVues: "765k",
        title: "Philippe Bihouix : Le mensonge de la croissance verte ? [EN DIRECT]",
        time: 6651,
        vues: 765000,
    },
    {
        rawTime: "1:35:01  ",
        rawVues: "95k",
        title: "L214 : Exploitation animale & Alimentation - Souffrance du 21ème siècle ? [EN DIRECT]",
        time: 5701,
        vues: 95000,
    },
    {
        rawTime: "1:22:38  ",
        rawVues: "83k",
        title: "Pollution atmosphérique : après l'amiante, un nouveau scandale d'Etat ? Solutions ? [EN DIRECT]",
        time: 4958,
        vues: 83000,
    },
    {
        rawTime: "57:38  ",
        rawVues: "174k",
        title: "Périco Légasse : Malbouffe et Mondialisation ? [EN DIRECT]",
        time: 3458,
        vues: 174000,
    },
    {
        rawTime: "47:22  ",
        rawVues: "1,1Mde",
        title: "Jean-Marc Jancovici : Anticiper l’effondrement énergétique ? [EN DIRECT]",
        time: 2842,
        vues: 1100000,
    },
    {
        rawTime: "2:02:52  ",
        rawVues: "205k",
        title: "Les Éconoclastes à l'École de Guerre : Le Jour d'après [EN DIRECT]",
        time: 7372,
        vues: 205000,
    },
    {
        rawTime: "1:15:03  ",
        rawVues: "625k",
        title: "Frédéric Taddeï : Les limites du débat ? [EN DIRECT]",
        time: 4503,
        vues: 625000,
    },
    {
        rawTime: "1:18:56  ",
        rawVues: "650k",
        title: "Cédric Villani : Intelligence artificielle perspectives futures [EN DIRECT]",
        time: 4736,
        vues: 650000,
    },
    {
        rawTime: "45:38  ",
        rawVues: "39k",
        title: "Philippe Tixier, Inventeur du Dirigeable du Futur ? [EN DIRECT]",
        time: 2738,
        vues: 39000,
    },
    {
        rawTime: "1:31:55  ",
        rawVues: "2,7Mde",
        title: "Changement de Civilisation ? Marc Luyckx Ghisi [EN DIRECT]",
        time: 5515,
        vues: 2700000,
    },
    {
        rawTime: "1:17:05  ",
        rawVues: "460k",
        title: "Laurent Alexandre : Intelligence artificielle [EN DIRECT]",
        time: 4625,
        vues: 460000,
    },
    {
        rawTime: "1:10:06  ",
        rawVues: "222k",
        title: "Bruno Parmentier : Nourrir l'humanité ? [EN DIRECT]",
        time: 4206,
        vues: 222000,
    },
    {
        rawTime: "1:02:02  ",
        rawVues: "459k",
        title: "Vincent Mignerot : Anticiper l'effondrement ? [EN DIRECT]",
        time: 3722,
        vues: 459000,
    },
    {
        rawTime: "1:03:50  ",
        rawVues: "591k",
        title: "Philippe Pascot, Corruption et Politique [EN DIRECT]",
        time: 3830,
        vues: 591000,
    },
    {
        rawTime: "1:13:21  ",
        rawVues: "539k",
        title: "Olivier Delamarche, Analyste financier [EN DIRECT]",
        time: 4401,
        vues: 539000,
    },
    {
        rawTime: "2:06:08  ",
        rawVues: "1,4Mde",
        title: "Étienne Chouard [EN DIRECT]",
        time: 7568,
        vues: 1400000,
    },
    {
        rawTime: "1:10:30  ",
        rawVues: "156k",
        title: 'Du Sextoy au "Dark Web" : Rayna Stamboliyska [EN DIRECT]',
        time: 4230,
        vues: 156000,
    },
    {
        rawTime: "43:38  ",
        rawVues: "161k",
        title: "Énergie nucléaire ? José Pluki [EN DIRECT]",
        time: 2618,
        vues: 161000,
    },
    {
        rawTime: "1:04:48  ",
        rawVues: "422k",
        title: "Benjamin Bayart, Grand Sorcier de l'Internet option vie privée [EN DIRECT]",
        time: 3888,
        vues: 422000,
    },
    {
        rawTime: "1:02:44  ",
        rawVues: "476k",
        title: "Guillaume Ancel, Lieutenant Colonel / Force d'action rapide [EN DIRECT]",
        time: 3764,
        vues: 476000,
    },
    {
        rawTime: "1:10:10  ",
        rawVues: "149k",
        title: "Stéphanie Gibaud, Lanceuse d'Alerte SwissLeaks [EN DIRECT]",
        time: 4210,
        vues: 149000,
    },
    {
        rawTime: "1:12:25  ",
        rawVues: "444k",
        title: "Juan Branco, avocat de Wikileaks [EN DIRECT]",
        time: 4345,
        vues: 444000,
    },
    {
        rawTime: "1:04:25  ",
        rawVues: "110k",
        title: "Lilian Thuram : football, racisme et géopolitique [EN DIRECT]",
        time: 3865,
        vues: 110000,
    },
];

const dataVideo = [
    {
        rawTime: "2:02:00  ",
        rawVues: "192k",
        title: "[VO] Mégamenaces, un avenir sombre, des politiques dans le déni ? Nouriel Roubini [EN DIRECT]",
        time: 7320,
        vues: 192000,
    },
    {
        rawTime: "2:10:49  ",
        rawVues: "137k",
        title: "La science-fiction prédit la guerre ? August Cole [VO]",
        time: 7849,
        vues: 137000,
    },
    {
        rawTime: "1:26:02  ",
        rawVues: "218k",
        title: "[VF] Julian Assange, torture made in Europe ? John Shipton [EN DIRECT]",
        time: 5162,
        vues: 218000,
    },
    {
        rawTime: "1:46:28  ",
        rawVues: "291k",
        title: "[ VF ] Collapsologie, anxiété et dépression ? Glenn Albrecht [EN DIRECT]",
        time: 6388,
        vues: 291000,
    },
    {
        rawTime: "1:02:48  ",
        rawVues: "117k",
        title: "Lutter sans violence ? Jean-Marie Muller [EN DIRECT]",
        time: 3768,
        vues: 117000,
    },
    {
        rawTime: "1:07:53  ",
        rawVues: "90k",
        title: "Mounir Mahjoubi, Ministre chargé du Numérique [EN DIRECT]",
        time: 4073,
        vues: 90000,
    },
    {
        rawTime: "1:04:09  ",
        rawVues: "80k",
        title: "la Nef - Banque éthique / Coopérative financière",
        time: 3849,
        vues: 80000,
    },
    {
        rawTime: "1:07:17  ",
        rawVues: "229k",
        title: "Sputnik France - Sans Filtre",
        time: 4037,
        vues: 229000,
    },
    {
        rawTime: "1:04:00  ",
        rawVues: "242k",
        title: "DATAGUEULE - Sans Filtre",
        time: 3840,
        vues: 242000,
    },
    {
        rawTime: "51:23  ",
        rawVues: "138k",
        title: "David Koubbi : Justice VS Finance",
        time: 3083,
        vues: 138000,
    },
    {
        rawTime: "1:09:32  ",
        rawVues: "278k",
        title: "France, terrorisme et diplomatie en carton",
        time: 4172,
        vues: 278000,
    },
    {
        rawTime: "49:18  ",
        rawVues: "128k",
        title: "États-Unis-Russie : Tensions Géopolitiques et Terrorisme",
        time: 2958,
        vues: 128000,
    },
    {
        rawTime: "44:43  ",
        rawVues: "113k",
        title: "Paul Watson, fondateur de Sea Shepherd : Plongée en eaux troubles",
        time: 2683,
        vues: 113000,
    },
    {
        rawTime: "1:05:24  ",
        rawVues: "91k",
        title: "Terrorisme VS Big Brother",
        time: 3924,
        vues: 91000,
    },
    {
        rawTime: "1:09:55  ",
        rawVues: "142k",
        title: "L'énergie des conflits, les conflits de l'énergie",
        time: 4195,
        vues: 142000,
    },
    {
        rawTime: "58:48  ",
        rawVues: "94k",
        title: "Henri Maler, ACRIMED : Discutons de l'information entre générations",
        time: 3528,
        vues: 94000,
    },
    {
        rawTime: "58:44  ",
        rawVues: "144k",
        title: "200 terroristes sur le territoire ? Entre Ukraine, Irak, Terrorisme, Reporter de Guerre et après ?",
        time: 3524,
        vues: 144000,
    },
    {
        rawTime: "1:19:00  ",
        rawVues: "217k",
        title: "David Koubbi, Affaire Kerviel, Justice et Société Générale ?",
        time: 4740,
        vues: 217000,
    },
    {
        rawTime: "49:58  ",
        rawVues: "1,4Mde",
        title: "Elise Lucet sans filtre, Cash investigation, Panama Papers, l'offensive des journalistes ?",
        time: 2998,
        vues: 1400000,
    },
    {
        rawTime: "59:49  ",
        rawVues: "1Mde",
        title: "Propagande de Guerre, festival de médias mensonges et complot ?",
        time: 3589,
        vues: 1000000,
    },
    {
        rawTime: "32:52  ",
        rawVues: "65k",
        title: "De l'éducation à la guerre ou De la guerre, à l'éducation ?",
        time: 1972,
        vues: 65000,
    },
    {
        rawTime: "1:09:38  ",
        rawVues: "216k",
        title: "Schizophrénie financière, casse du siècle ou injure sur l'avenir ?",
        time: 4178,
        vues: 216000,
    },
    {
        rawTime: "1:07:04  ",
        rawVues: "606k",
        title: "Natacha Polony : Police de la pensée, journalistes en laisse ?",
        time: 4024,
        vues: 606000,
    },
    {
        rawTime: "1:09:02  ",
        rawVues: "236k",
        title: "Charlie Hebdo sans filtre par Denis Robert",
        time: 4142,
        vues: 236000,
    },
    {
        rawTime: "1:19:59  ",
        rawVues: "71k",
        title: "Ambassadeur de Russie face à l'augmentation des tensions",
        time: 4799,
        vues: 71000,
    },
    {
        rawTime: "1:24:54  ",
        rawVues: "161k",
        title: "Terrorisme, Etat d'Urgence, où sont les solutions ? Journaliste, Renseignement, Stratégiste, Hacker.",
        time: 5094,
        vues: 161000,
    },
    {
        rawTime: "1:19:22  ",
        rawVues: "260k",
        title: "Géopolitique, Russie, Terrorisme, Finance - 6/11/15",
        time: 4762,
        vues: 260000,
    },
    {
        rawTime: "1:13:29  ",
        rawVues: "194k",
        title: "Crédit Mutuel, Censure, Bolloré, Canal+ et TAFTA | Guerre contre le journalisme",
        time: 4409,
        vues: 194000,
    },
    {
        rawTime: "31:38  ",
        rawVues: "286k",
        title: "Pierre Conesa : Arabie Saoudite, Théâtre de Dupes, Stratégie planétaire. (Ex Affaires Stratégiques)",
        time: 1898,
        vues: 286000,
    },
    {
        rawTime: "47:46  ",
        rawVues: "104k",
        title: "Député, qui va payer ? Entre TAFTA, Monsanto et la Syrie ? (Jean Lassalle)",
        time: 2866,
        vues: 104000,
    },
    {
        rawTime: "45:30  ",
        rawVues: "103k",
        title: "CGT-Police et Loi renseignement",
        time: 2730,
        vues: 103000,
    },
    {
        rawTime: "1:17:47  ",
        rawVues: "110k",
        title: "Pétrole et gaz de schiste, où va-t-on ?",
        time: 4667,
        vues: 110000,
    },
    {
        rawTime: "1:03:32  ",
        rawVues: "40k",
        title: "Ministre, Loi renseignement, Stratégie européenne",
        time: 3812,
        vues: 40000,
    },
    {
        rawTime: "1:07:28  ",
        rawVues: "52k",
        title: "Terrorisme/Internet : Liberté d'expression menacée en France ?",
        time: 4048,
        vues: 52000,
    },
    {
        rawTime: "31:01  ",
        rawVues: "77k",
        title: "Religion, Terrorisme et paradis. Pierre Conesa ( Ex Affaires Stratégiques )",
        time: 1861,
        vues: 77000,
    },
    {
        rawTime: "1:45:25  ",
        rawVues: "166k",
        title: "USA, Europe, LuxLeaks : Le grand marché des inégalités",
        time: 6325,
        vues: 166000,
    },
    {
        rawTime: "1:14:29  ",
        rawVues: "211k",
        title: "Interview Pierre Conesa. Politique de contre-radicalisation en France ( Ex Affaires stratégiques )",
        time: 4469,
        vues: 211000,
    },
    {
        rawTime: "26:46  ",
        rawVues: "23k",
        title: "Reporter de guerre et journaliste : Bob Coen et Eric Nadler",
        time: 1606,
        vues: 23000,
    },
    {
        rawTime: "2:58  ",
        rawVues: "30k",
        title: "Les Econoclastes",
        time: 178,
        vues: 30000,
    },
    {
        rawTime: "33:48  ",
        rawVues: "51k",
        title: "Benjamin Bayart - Neutralité du net",
        time: 2028,
        vues: 51000,
    },
    {
        rawTime: "27:45  ",
        rawVues: "34k",
        title: "Gilles Babinet - Le Big Data",
        time: 1665,
        vues: 34000,
    },
    {
        rawTime: "24:45  ",
        rawVues: "28k",
        title: 'Hacker VS Justice - Affaire "Bluetouff" (O. Iteanu)',
        time: 1485,
        vues: 28000,
    },
    {
        rawTime: "1:02:12  ",
        rawVues: "58k",
        title: "Où va le monde financier ? (J-M. Rozan & H. de Carmoy)",
        time: 3732,
        vues: 58000,
    },
    {
        rawTime: "1:41  ",
        rawVues: "29k",
        title: "Réalité bancaire camouflée, imposture des journalistes ?",
        time: 101,
        vues: 29000,
    },
    {
        rawTime: "16:09  ",
        rawVues: "55k",
        title: "Allons nous vers une Cyber Dictature ? E. Filiol (ex DGSE, hacker) , J. Zimmermann (QDN)",
        time: 969,
        vues: 55000,
    },
    {
        rawTime: "37:40  ",
        rawVues: "29k",
        title: "Loi de programmation militaire et neutralité du réseau, vie privée et démocratie en danger ?",
        time: 2260,
        vues: 29000,
    },
    {
        rawTime: "1:41:43  ",
        rawVues: "88k",
        title: "H. de Carmoy, P. Béchade, O.Delamarche, O.Berruyer : Réfléchissons ensemble",
        time: 6103,
        vues: 88000,
    },
    {
        rawTime: "44:35  ",
        rawVues: "57k",
        title: "Michel Éléftériadès",
        time: 2675,
        vues: 57000,
    },
    {
        rawTime: "1:02:35  ",
        rawVues: "80k",
        title: "Peter Dale Scott",
        time: 3755,
        vues: 80000,
    },
    {
        rawTime: "41:41  ",
        rawVues: "58k",
        title: "Denis Robert (journaliste, écrivain, whistleblower)",
        time: 2501,
        vues: 58000,
    },
    {
        rawTime: "5:18  ",
        rawVues: "5,7k",
        title: "Thinkerview - (Trailer) Interview de Denis Robert (journaliste, écrivain, whistleblower)",
        time: 318,
        vues: 5000,
    },
    {
        rawTime: "23:04  ",
        rawVues: "96k",
        title: "Jérémie Zimmermann",
        time: 1384,
        vues: 96000,
    },
    {
        rawTime: "22:15  ",
        rawVues: "189k",
        title: "Eric Filiol (hacker, cryptanalyste, ancien de la DGSE)",
        time: 1335,
        vues: 189000,
    },
    {
        rawTime: "16:26  ",
        rawVues: "93k",
        title: "Alain Chouet (Ancien chef de service à la D.G.S.E.)",
        time: 986,
        vues: 93000,
    },
    {
        rawTime: "1:21:57  ",
        rawVues: "81k",
        title: "B.Esambert, O.Delamarche, O.Berruyer : Réfléchissons ensemble",
        time: 4917,
        vues: 81000,
    },
    {
        rawTime: "36:52  ",
        rawVues: "107k",
        title: "Olivier Delamarche",
        time: 2212,
        vues: 107000,
    },
    {
        rawTime: "40:20  ",
        rawVues: "83k",
        title: "Jacques Blamont",
        time: 2420,
        vues: 83000,
    },
];
